# Database kind
quarkus.datasource.db-kind=postgresql

# Database credentials
quarkus.datasource.username=user
quarkus.datasource.password=password

# JDBC connection URL
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ai_analysis_db

# Liquibase, changelog mapca
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# Hibernate, ce sm prov razumu forum to pomen da hibernate ne bo sam kreiral tabel ampak bo to delal liquibase
# aka entities ne bodo sami generiral tabel
# 1. liquidbase table za management v changelogu
# 2. potem kopiramo in naredimo entity
quarkus.hibernate-orm.schema-management.strategy=none


# mel sm neke probleme z indexiranjem entityjev in servicejev, quarkus jih ni najdu, to + META-INF/beans.xml je bla resitev
quarkus.index-dependency.entity.group-id=com.ales.aianalysis
quarkus.index-dependency.entity.artifact-id=entity

quarkus.index-dependency.service.group-id=com.ales.aianalysis
quarkus.index-dependency.service.artifact-id=service

# api/src/main/resources/application.properties
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.5-flash