package com.ales.aianalysis.entity;


import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/*
OPIS - 
osnovna entiteta za analize, predstavlja določeno analizo, metadata
*/



@Getter
@Setter
@NoArgsConstructor

@Entity
@Table(name = "analysis")
public class Analysis {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String title;

    private String description;

    @Column(name = "public_code", unique = true, nullable = false)
    private String publicCode;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;


    //all args kontruktor addou manualy ker sm ugotovu da mi lombok daje kontruktor z id-jem, kar je pa narobe ker je autogenerated
    public Analysis(String title, String description, String publicCode, LocalDateTime createdAt) {
        this.title = title;
        this.description = description;
        this.publicCode = publicCode;
        this.createdAt = createdAt;
    }
}
